config/routes.rb
Rails.application.routes.draw do
  root 'documents#index'

  scope path: '/documents', controller: :documents do
    post 'new' => :new, :as => :new_document
  end
  resources :documents, only: [:index, :create]
  resources :translations, only: :create
end

app/models/document.rb
class Document
  
  include ActiveAttr::Model
  include ActiveAttr::Attributes
  include ActiveAttr::MassAssignment  
  include ActiveAttr::QueryAttributes
 
  attribute :src_file_name 
#  attribute :src_content 
  attribute :trgt_file_name 
  attribute :trgt_lang_code 
#  attribute :src_is_draft 
  attribute :trgt_is_draft 
  attribute :document_row

  attr_accessor  :src_lang_code, :trgt_file_name, :trgt_lang_code, 
    :trgt_is_draft, :document_row
# :src_content,  :src_is_draft,


# def save
#   if @src_is_draft
#     src_content = @src_content['source']
#     trgt_content = @src_content['target']
#   else
#     src_content = @src_content
#   end
#   @src_lang_code, src_hash_content = src_content.first
#   @trgt_lang_code, trgt_hash_content = trgt_content.first if !trgt_content.nil? 
#   plain_content = plain_hash({ 'lang_code' => src_hash_content }, { 'lang_code' => trgt_hash_content } || {})
#   i = -1
#   plain_content.map { |k, v| plain_content[k].merge!(id: i+=1) }
#
#   @document_row ||= []
#   plain_content.each do |key, value|
#     @document_row.push(DocumentRow.new(value))
#   end
#   @trgt_is_draft = false
#   valid?
# end
  
  def document_row_attributes=(attributes)
    @document_row ||= []
    attributes.each do |i, row_params|
      @document_row.push(Row.new(row_params))
    end
  end
  
# def plain_hash(h, h2, level = 0, t_id = "", t_path = "", r = {})
#   h.each_pair do |key, value|
#     id = (!t_id.empty? ? "#{ t_id }_" : t_id) + "#{ key }"
#     path = t_path + "[#{ key }]"
#     r[id] = { key: key, path: path, is_group: true, level: level }
#     if h[key].class == Hash
#       plain_hash(h[key], h2[key]||{}, level + 1, id, path, r)
#     else
#       r[id][:src_value] = value
#       r[id][:trgt_value] = h2[key] || ''
#       r[id][:is_group] = false
#     end
#   end
#   return r
# end

end

app/models/document_row.rb
class DocumentRow
  include ActiveAttr::Model
  include ActiveAttr::MassAssignment

  attribute :id
  attribute :key 
  attribute :path 
  attribute :is_group 
  attribute :level 
  attribute :src_value 
  attribute :trgt_value
      
end

app/models/translator.rb
class Translator
  include ActiveModel::Model

  class << self

    attr_accessor :enabled, :dirs, :from_code

    def enabled?
      @enabled
    end

    def lang_list
      @dirs ||= []
      @from_code ||= ''
      LOCALES_LIST.map {|k, v| [ "#{ v['name'] } (#{ k })" + (@dirs.select { |e| e =~ /#{ @from_code }-#{ k }/ }.present? ? " *" : ""), k ]}
    end
  
    def lang_name(code)
      @dirs ||= []
      "#{ LOCALES_LIST[code]['name'] } (#{ code })" + (@dirs.select { |e| e =~ /#{ code }-/ }.present? ? " *" : "")
    end
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_locale
  
  private
  
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    PrepareTranslator.call
  end
 
  def new
    @document = Document.new()
    uploading = UploadSource.call(document: @document, src_file: params[:src_file])
    if uploading.success?
      Translator.from_code = @document.src_lang_code      
      status = AJAX_STATUS_OK 
    else
      flash[:danger] = uploading.error
      status = AJAX_STATUS_ERROR
    end     
    render :formats => [:js], status: status
 end

  def create
    creation = CreateFile.call(params: params)
    if creation.success?
      send_data creation.content, :filename => creation.file_name
    else
      flash[:danger] = creation.error
      render :formats => [:js]
    end      
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController

  def create
    creation = CreateTranslation.call(params)
    if creation.success?
      @target = creation.result
      status = AJAX_STATUS_OK
    else
      flash[:danger] = creation.error 
      status = AJAX_STATUS_ERROR
    end
    render :formats => [:js], status: status
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def app_current_locale
    t("app.locale_list.#{ I18n.locale }")
  end
  
  def app_locales_list
    l_list = ''
    I18n.available_locales.each do |i|
     l_list << content_tag(:li, link_to(t("app.locale_list.#{ i }"), root_path(locale: i))) if i != I18n.locale
    end
    l_list.html_safe   
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
  def get_uls(prev_level, level)
    ("</ul>" * (prev_level - level)).html_safe if level < prev_level
  end

  def get_attributes(is_group, id)
    key_class = is_group ? "bg-info glyphicon glyphicon-minus-sign" : "bg-warning"
    transl_class = "inner glyphicon glyphicon-play-circle " + ( id.zero? ? "auto-transl-all" : "auto-transl")
    transl_id = is_group ? (id.zero? ? "auto-transl-all" : "") : "auto-transl-#{id}"
    transl_title =  id.zero? ? t('form.title.translate_all') : t('form.title.translate_this')
    [key_class, transl_class, transl_id, transl_title]      
  end
  
  def get_ulorli(is_group)
    is_group ? "<ul>".html_safe : "</li>".html_safe
  end
  
  def get_ullis(level, id, size)
    ("</ul></li>" * (level - 1)).html_safe if id == (size - 1)
  end
end

app/views/documents/_button_save.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" id="save-button" data-toggle="dropdown" aria-expanded="false" title='<%= t('button.title.save') %>'>
    <span class="glyphicon glyphicon-save" aria-hidden="true"></span> <%= t('button.save') %> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu upload-save" role="menu">
    <li>
    	<a href="" id="save-locale" title='<%= t('button.title.save_locale') %>'><%= t('button.locale') %></a>​
   	</li><li>
   		<a href="" id="save-draft" title='<%= t('button.title.save_draft') %>'><%= t('button.draft') %></a>​
  	</li>
  </ul>
</div>

app/views/documents/_button_upload.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" title='<%= t('button.title.upload') %>'>
    <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> <%= t('button.upload') %> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu upload-save" role="menu">
    <li>
    	<a href="" id="upload-locale" title='<%= t('button.title.upload_locale') %>'><%= t('button.locale') %></a>​
   </li><li>
   		<a href="" id="upload-draft" title='<%= t('button.title.upload_draft') %>'><%= t('button.draft') %></a>​
   </li>
  </ul>
</div>

app/views/documents/_form_upload.html.erb
<%= form_tag new_document_path, id: "upload-form", remote: true do %>
  <%= file_field_tag "src_file", id: "src-file", style: "display: none;" %>
  <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
<% end %>

app/views/documents/_table.html.erb
<%= form_for @document, html: {class: "form-inline", id: "transl-form"} do |f| %>
	<div class="row">
		<%= render 'button_upload' %>
	  <%= f.text_field :src_file_name,  id: "src-file-name", :readonly => true, class: "form-control", title: t('form.title.source_file') %>
	  <%= f.hidden_field :src_lang_code, id: "src-lang-code" %>
	  <%= text_field_tag 'src_lang', Translator.lang_name(@document.src_lang_code), id: "src-lang", :readonly => true, class: "form-control", title: t('form.title.source_lang') %>
	  <%= tag('span', class: "glyphicon glyphicon-arrow-right transl-sign") %> 
	  <%= f.select :trgt_lang_code, options_for_select(Translator.lang_list, @document.trgt_lang_code), {}, {id: "trgt-lang", class: "form-control inline-block", title: t('form.title.target_lang')} %>
	  <%= f.text_field :trgt_file_name, :placeholder => "_locale_.yml", id: "trgt-file-name", class: "form-control", title: t('form.title.target_file') %>
	  <%= f.hidden_field :trgt_is_draft, id: 'trgt-is-draft' %>
		<%= render 'button_save' %>
	</div>	

	<div class="row">
	  <div class="tree">
	    <% prev_level, size = -1, @document.document_row.count %>
	    <ul>
				<%= f.fields_for :document_row do |rf| %>
					<% id, key, is_group, level, path, value = rf.object.id, rf.object.key, rf.object.is_group, rf.object.level, rf.object.path, rf.object.src_value %>
          <% key_class, transl_class, transl_id, transl_title = get_attributes is_group, id %>
	        <%= get_uls prev_level, level %>
	        <li>

						<span class="<%=key_class%>"> 
						  <%= key %> 
					    <%= tag('span', class: transl_class, title: transl_title, id: transl_id) if !is_group || id.zero? %>
						</span>

					  <%= hidden_field_tag("src_plain_array[#{ id }]", value) unless is_group %>
	          <%= rf.text_area(:src_value, name: "src_array#{ path }", id: "src-array-#{ id }", class: "form-control long", :readonly => true) unless is_group %>
	          <%= rf.text_area(:trgt_value, name: "trgt_array#{ path }", id: "trgt-array-#{ id }", class: "form-control long") unless is_group %>

	          <%= get_ulorli is_group %>
	          <%= get_ullis level, id, size %>
	
	          <% prev_level = level %>
		  	<% end %>
	    </ul>
	  </div>
	</div>
<% end %>

app/views/documents/index.html.erb
<%= render 'layouts/set_locale' %>

<%= render 'form_upload' %>

<div id='upload-button'>
	<%= content_tag('div', render('button_upload'), class: 'row') %>
</div>
	
<%= content_tag('div', '', id: 'transl-table') %>

app/views/documents/new.js.erb
<% unless flash[:danger] %>
  $( '#app-locale-list' ).attr( "data-disabled", "true" );
  $( '#upload-button' ).html( "<%= j "" %>" )
  $( '#transl-table' ).html( "<%= j "#{render 'table'}".html_safe %>" )
	translateFormInit();
<% end %>

app/views/documents/table.js.erb
<% unless flash[:danger] %>
  $( '#upload-button' ).html( "<%= j "" %>" )
  $( '#transl-table' ).html( "<%= j "#{render 'table'}".html_safe %>" )
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class = "col-md-6">
    This project on 
    <%= link_to "GitHub", "https://github.com/lemboy/locales_translator2" %>
  </div>
  <div class = "col-md-6 text-right">
    <% if Translator.enabled? %>
      <%= content_tag(:div, link_to("Powered by Yandex.Translate", "http://translate.yandex.com/")) %>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">

  	  <div class="navbar-header">
        <div class="navbar-brand">Locales Translator</div>
      </div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-left">
					<% if Translator.enabled? %>
						<%= content_tag(:span, t('translation.mt_enabled'), title: t('translation.title.mt_enabled'), class: 'label label-success') %>
				 	<% else %>
				  	<%= content_tag(:span, t('translation.mt_disabled'), title: t('translation.title.mt_disabled'), class: 'label label-warning') %>
					<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
			    <li class="dropdown app-locale-list">
			      <a href="#" class="dropdown-toggle" id="app-locale-list" data-toggle="dropdown" role="button" aria-expanded="false"><%= app_current_locale %> <span class="caret"></span></a>
			      <ul class="dropdown-menu app-locale-list" role="menu">
							<%= app_locales_list %>							 
			      </ul>
			    </li>
			  </ul>
			</div>

    </div>
  </nav>
</header>

app/views/layouts/_set_locale.erb
<script type="text/javascript">
  I18n.defaultLocale = "<%= I18n.default_locale %>";
  I18n.locale = "<%= I18n.locale %>";
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locales Translator</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/set_locale' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id='wrap'>
      <div class='container'>
		    <%= render 'shared/flash_message' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>
	

app/views/layouts/application.js.erb
<%= yield %>
 
<%= render 'shared/flash_message' %>

app/views/shared/_flash_message.html.erb
<div id='flash-message' style="display: none;">	
  <button type="button" id="flash-message-button" class="close" style="display: none;">
     &times;
  </button>
	<div id='flash-message-body'></div>
</div>

app/views/shared/_flash_message.js.erb
cleanMessage();
<% unless flash.empty? %>
  <% flash.each do |key, value| %>
		<% if key.include?('danger') %>
			$( '#flash-message-button' ).show();
		<% end %>
    $( "#flash-message" ).addClass( "<%= "alert alert-#{key}" %>"  );
    $( "#flash-message-body" ).html( "<%= j "#{flash.discard(key)}" %>" );
	<% end %>
  setTimeout( function() { cleanMessage(); }, 30000 );
<% end %>

app/views/translations/create.js.erb
<% unless flash[:danger] %>
  <% @target.each do |k, v| %>         
    $( "<%= "#trgt-array-#{k}" %>" ).val("<%= j v %>");
  <% end %>
<% end %>